//Auth
export const ASYNC_ACTION_START = 'ASYNC_ACTION_START';

//Product
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const SHOW_PRODUCT = 'SHOW_PRODUCT';
export const UPDATE_PRODUCT_AFTER_DELETE='UPDATE_PRODUCT_AFTER_DELETE';
export const UPDATE_PRODUCT_AFTER_ADD='UPDATE_PRODUCT_AFTER_ADD';
export const SHOW_PRODUCT_DETAILS = 'SHOW_PRODUCT_DETAILS';
// export const Show_Product = 'Show_Product';

//Sale
export const CHECK_OPEN_BAG= 'CHECK_OPEN_BAG';
export const UPDATE_OPENORDER='UPDATE_OPENORDER';
export const CREATE_ORDER = 'CREATE_ORDER';
export const ADD_ORDERITEM = 'ADD_ORDERITEM';
export const UPDATE_ORDER= 'UPDATE_ORDER';
export const UPDATE_ORDER_ITEM = 'UPDATE_ORDER_ITEM';
export const Delete_ORDER_ITEM = 'Delete_ORDER_ITEM';
export const CREATE_SOLD_AND_EXIST_LIST = 'CREATE_SOLD_AND_EXIST_LIST';

//lang
export const SET_LANGUAGE_TEXT='SET_LANGUAGE_TEXT';